site_name: RD-Gen API document
site_url: https://github.com.io/azu-lab/RD-Gen
repo_url: https://github.com/azu-lab/RD-Gen
edit_uri: edit/master/
docs_dir: docs

theme:
  name: material
  features:
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
  language: en
  palette:
    - scheme: slate
      primary: grey

extra:
  font:
    text: Oxygen
    code: Oxygen Mono
  version:
    provider: mike

extra_css:
  - https://unpkg.com/mermaid@8.13.10/dist/mermaid.css
  - assets/css/extra.css
  - https://use.fontawesome.com/releases/v5.15.4/css/all.css

extra_javascript:
  - https://unpkg.com/mermaid@8.13.10/dist/mermaid.min.js
  - https://cdn.jsdelivr.net/npm/mathjax@2/MathJax.js?config=TeX-AMS-MML_HTMLorMML

plugins:
  - awesome-pages
  - exclude:
      regex:
        - ^(?!(.*/)?assets/).*\.(?!(.*\.)?md|(.*\.)?svg|(.*\.)?png|(.*\.)?jpg).*$
        - ^(.*/)?[^.]*$
  - macros
  - same-dir
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: numpy
            show_source: false
            show_submodules: false

markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - fontawesome_markdown
  - footnotes
  - mdx_math
  - mdx_truly_sane_lists:
      nested_indent: 2
  - plantuml_markdown:
      server: http://www.plantuml.com/plantuml
      format: svg
  - pymdownx.arithmatex
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: "#"
