name: deploy-docs

on:
  push:
    branches:
      - main
      - galactic
    paths:
      - mkdocs.yaml
      - "**/*.md"
      - "**/*.svg"
      - "**/*.png"
      - "**/*.jpg"
      - "**/*.py"
  pull_request_target:
    types:
      - opened
      - synchronize
      - labeled
  workflow_dispatch:

jobs:
  prevent-no-label-execution:
    uses: ./.github/workflows/prevent-no-label-execution.yaml@v1
    with:
      label: deploy-docs

  deploy-docs:
    needs: prevent-no-label-execution
    if: ${{ needs.prevent-no-label-execution.outputs.run == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Deploy docs
        uses: ./.github/workflows/deploy-docs-sub@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          latest: ${{ github.event_name != 'pull_request_target' && github.ref_name == github.event.repository.default_branch }}
          mkdocs-requirements-txt: ./mkdocs-requirements.txt
